services:

  client:
    image: to_do_list_frontend:0.01
    container_name: td_frontend
    ports:
      - "3000:80"

  backend:
    image: to_do_list_backend:0.01
    container_name: td_backend
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=mysql://user:secret@todo_db:3306/todos
    depends_on:
      todo_db:
        condition: service_healthy

  todo_db:
    image: mysql:latest
    container_name: todo_db
    ports:
      - "3306:3306"
    command: --init-file /data/application/init.todo.sql
    volumes:
      - ../backend/init.todo.sql:/data/application/init.todo.sql
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=todos
      - MYSQL_USER=user
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_HOST=%    
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'todo_db', '-u$$MYSQL_ROOT_USER', '-p$$MYSQL_ROOT_PASSWORD' ]
      timeout: 5s
      retries: 10